# Generated by Django 5.1.6 on 2025-03-04 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['description']},
        ),
    ]
