# Generated by Django 5.1.6 on 2025-03-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created_at']},
        ),
    ]
